- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://44.197.172.75:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipeline_jobs }}"